<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>User Management Export</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h2 {
            margin: 0;
            padding: 0;
            color: #000000ff;
        }
        .header p {
            margin: 5px 0 0 0;
            color: #64748B;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            padding: 10px;
            border: 1px solid #E2E8F0;
            text-align: left;
        }
        th {
            font-weight: bold;
            color: #475569;
        }
        tr:nth-child(even) {
        }
        .footer {
            text-align: right;
            margin-top: 30px;
            font-size: 10px;
            color: #94A3B8;
        }
        .status {
            text-transform: capitalize;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>User Management Data</h2>
        <p>Export Date: {{ date('d M Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>No</th>
                <th>Name</th>
                <th>Email</th>
                <th>NIM</th>
                <th>Program Studi</th>
                <th>Status</th>
                <th>Joined Date</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $index => $user)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $user['name'] }}</td>
                <td>{{ $user['email'] }}</td>
                <td>{{ $user['nim'] }}</td>
                <td>{{ $user['prodi'] }}</td>
                <td class="status">{{ $user['status'] }}</td>
                <td>{{ $user['joined'] }}</td>
            </tr>
            @empty
            <tr>
                <td colspan="7" style="text-align: center;">No users found</td>
            </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        Generated by YouniFirst System
    </div>
</body>
</html>
